wip: external skia build
Something about missing a symbol when compiled, ugh

slint-cpp>   cargo:rerun-if-changed=/nix/store/xjh9jk58nn5idi9l3i9pxf6z5axjwwwy-rust-skia-m135-0.83.1/include
slint-cpp>   COMPILING BINDINGS: ["src/bindings.cpp", "src/gl.cpp", "src/vulkan.cpp", "src/gpu.cpp", "src/shaper.cpp", "src/paragraph.cpp"]
slint-cpp>     DEFINES: NDEBUG= SKIA_IMPLEMENTATION=1 SK_CODEC_DECODES_BMP= SK_CODEC_DECODES_ICO= SK_CODEC_DECODES_JPEG= SK_CODEC_DECODES_PNG= SK_CODEC_DECODES_PNG_WITH_LIBPNG= SK_CODEC_DECODES_WBMP= SK_CODEC_DECODES_WEBP= SK_CODEC_ENCODES_JPEG= SK_CODEC_ENCODES_PNG= SK_CODEC_ENCODES_PNG_WITH_LIBPNG= SK_CODEC_ENCODES_WEBP= SK_DISABLE_TRACING= SK_ENABLE_AVX512_OPTS= SK_ENABLE_PRECOMPILE= SK_FONTMGR_ANDROID_AVAILABLE= SK_FONTMGR_FCI_AVAILABLE= SK_FONTMGR_FONTCONFIG_AVAILABLE= SK_FONTMGR_FREETYPE_DIRECTORY_AVAILABLE= SK_FONTMGR_FREETYPE_EMBEDDED_AVAILABLE= SK_FONTMGR_FREETYPE_EMPTY_AVAILABLE= SK_GAMMA_APPLY_TO_A8= SK_GANESH= SK_GL= SK_PDF_USE_HARFBUZZ_SUBSET= SK_R32_SHIFT=16 SK_SUPPORT_PDF= SK_TYPEFACE_FACTORY_FREETYPE= SK_USE_INTERNAL_VULKAN_HEADERS= SK_USE_PERFETTO= SK_USE_VMA= SK_VULKAN= SK_XML=
slint-cpp>     ARGS: -std=c++17 -fno-rtti
slint-cpp>   cargo:warning=src/shaper.cpp:69:22: error: no member named 'MakeIcuBiDiRunIterator' in 'SkShaper'; did you mean 'MakeBiDiRunIterator'?
slint-cpp>   cargo:warning=   69 |     return SkShaper::MakeIcuBiDiRunIterator(utf8, utf8Bytes, bidiLevel).release();
slint-cpp>   cargo:warning=      |            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
slint-cpp>   cargo:warning=      |                      MakeBiDiRunIterator
slint-cpp>   cargo:warning=/nix/store/xjh9jk58nn5idi9l3i9pxf6z5axjwwwy-rust-skia-m135-0.83.1/include/modules/skshaper/include/SkShaper.h:145:5: note: 'MakeBiDiRunIterator' declared here
slint-cpp>   cargo:warning=  145 |     MakeBiDiRunIterator(const char* utf8, size_t utf8Bytes, uint8_t bidiLevel);
slint-cpp>   cargo:warning=      |     ^
slint-cpp>   cargo:warning=src/shaper.cpp:81:22: error: no member named 'MakeHbIcuScriptRunIterator' in 'SkShaper'
slint-cpp>   cargo:warning=   81 |     return SkShaper::MakeHbIcuScriptRunIterator(utf8, utf8Bytes).release();
slint-cpp>   cargo:warning=      |            ~~~~~~~~~~^
slint-cpp>   cargo:warning=2 errors generated.